# version: '3'
# services: 
#   ddn:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - sqlite
#       # - mysql
#     networks:
#       - docker_ddn
#     ports:
#       - 8001:8001

#   sqlite:
#     image: nouchka/sqlite3:latest
#     stdin_open: true
#     tty: true
#     volumes:
#       - ddn-sqlite:/root/db/
#     networks:
#       - docker_ddn

#   # mysql:
#   #   image: mysql:5
#   #   restart: always
#   #   environment:      
#   #     - MYSQL_ROOT_PASSWORD=root
#   #   volumes:
#   #     - ddn-mysql:/data
#   #   networks:
#   #     - docker_ddn
#   #   ports:
#   #     - 13306:3306

# volumes:
#   ddn-sqlite:
#   # ddn-mysql:

# networks:
#   docker_ddn:
#     driver: bridge

version: '3'
services: 
  ddn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./app/ddn/constants/constants.js:/ddn/constants/constants.js
      - ./app/ddn/config/genesisBlock.json:/ddn/config/genesisBlock.json
      - ./app/ddn/db:/ddn/db
      - ./app/ddn/logs:/ddn/logs
      - ./app/ddn/.ddnrc.js:/ddn/.ddnrc.js
    tty: true  # Dockerfile没有前台运行程序，所以启动后容器就会停止，这个是个伪前台运行配置，保证容器运行